### ISSUE TITLE
Unnecesary copying and high memory usage

### ISSUE THREAD

**Issue by brano543** [RoutingKit/RoutingKit#10]
Hello,
first i would like to thank the authors of the library for their great work. The library is excellent and save me many hours, because the implementation of contraction hierarchies is easy to use, fast and memory efficient. 

However, i have notice three places where high memory usage occurs. 
1) For some reason the ContractionHierarchy::build method creates copies of input objects instead of passing parameters by reference. I know it is noted in documentation,but even for small country dataset it doubles the memory needed for preprocessing stage. I can not imagine doing this for bigger datasets as one will soon run out of memory.

2) After arcs are sorted and loops are removed, the class Graph for some reason inserts every edge twice. I have looked up on what parser does, it distinguishes between forward and backward edges and add forward,backward or both edges to head and tail. So for instance if i have edges (1,2) and (2,1). These lines

```
	for(unsigned a=0; a<head.size(); ++a){
				unsigned x = tail[a];
				unsigned y = head[a];
				unsigned w = weight[a];

				
				if(x != y){
					out_[x].push_back({y, w, 1, invalid_id});
					in_[y].push_back({x, w, 1, invalid_id});
				}
			}
```
insert into those arrays 2 entries each instead of one.

3) The members of class ContractionHierarchyQuery are arrays of node count length. For instance vector in TimestampFlags and the vectors which keep reference to best parent and best tentative distance could be replaced by hash map.

If you would like, i can help you fix those problems and make this library better suited for country datasets

**Comment by ben-strasser** [comment]
Hi,

> first i would like to thank the authors of the library for their great work.

Thanks for the feedback, you're welcome.

> The library is excellent and save me many hours, because the implementation of contraction hierarchies is easy to use, fast and memory efficient.

We are always interested in hearing about the applications that people use our code in. Would you mind giving us a few pointers?

> However, i have notice two places where high memory usage occurs.

What hardware and what graph sizes do you have in mind?

Our usual (West-)Europe test graph easily fits into a standard 8 GB RAM Laptop.

> 1) For some reason the ContractionHierarchy::build method creates copies of input objects instead of passing parameters by reference. I know it is noted in documentation,but even for small country dataset it doubles the memory needed for preprocessing stage. I can not imagine doing this for bigger datasets as one will soon run out of memory.

If you do not need the original arrays at the caller side anymore, then you can just use std::move and avoid the copy.

The build function sorts the arrays, i.e., it needs mutable access to the arrays. const& therefore requires an internal copy to take place. On the other hand pass-by-value allows to avoid the copy if std::move is used. The second option is therefore sometimes better and never worse.

Another option would be pass-by-non-const-ref and document that the arc IDs are reassigned in an unpredictable way. This would definitely cause hard to find bugs - not a good idea. But let's disregard that argument for a moment. The build function can only reorder the arrays it is passed. If there are other attributes out there, such as for example a speed array, then those would not be reordered. As the user nearly always has additional attributes, he will nearly always need to do a manual copy.

In nearly all use cases there will be a copy, so we just go with the most flexible and easiest to use syntax, which also allows stuff such as:

```cpp
vector<unsigned>tail,head,weight1,weight2;
ContractionHierarchy ch1, ch2;
thread a([&]{ch1 = ContractionHierarchy::build(tail, head, weight1);});
thread b([&]{ch2 = ContractionHierarchy::build(tail, head, weight2);});
a.join(); b.join();
```

to just work as expected.

Further the space consumption of the tail and head arrays should be dominated by other internal structures, so it should not really matter.

> 2) After arcs are sorted and loops are removed, the class Graph for some reason inserts every edge twice.

You need arcs in both directions to run a bidirectional Dijkstra search. Without bidirectional Dijkstra you would significantly increase the preprocessing time.

You could reduce memory consumption for undirected input graphs. However, I do not see enough applications with undirected graphs to warrant a special code path, that needs to be maintained separately.

> 3) The members of class ContractionHierarchyQuery are arrays of node count length. For instance vector in TimestampFlags and the vectors which keep reference to best parent and best tentative distance could be replaced by hash map.

A hash map access is significantly slower than an array access. Hash maps are definitely not the default data structure that you want to have here. I could picture a specialized query class with reduced memory consumption but that only makes sense if you have many query objects simultaneously. The idea is to have one object per worker thread, i.e., only very few.

Best Regards
Ben Strasser

**Comment by brano543** [comment]
> What hardware and what graph sizes do you have in mind? Our usual (West-)Europe test graph easily fits into a standard 8 GB RAM Laptop.

I am using Intel Core i7-940 which has 4 cores and can handle 8 threads with 12 GB RAM. I am using my own parsing application based on LibOsmium. I have examined your parser and you remove a lot of edges from the graph. This is why you don´t need so much space. For instance for 170 MB PBF Slovakia country extract i insert 4 million edges, while you insert just 1 million. I was having trouble nicely printing path,because there were some really sharp edges between points and this created line segment which was outside of road printed on OpenStreetMap road.

> You need arcs in both directions to run a bidirectional Dijkstra search. Without bidirectional Dijkstra you would significantly increase the preprocessing time.

I have looked more deeply into the code and i now understand why you need those two arrays in and out. You need it,because you need to go some "hops" behind and forward from given node. This is why i had so much trouble implementing Contraction Hierarchies myself, because i couldn´t solve how to efficiently implement this.  Others library i looked into (Monav) used some kind of graph that used only one edge array, but i am not sure how did they distinguished between in and out edges for given node,since they called 
```
 _DynamicGraph::EdgeIterator inEdge = _graph->BeginEdges( node ), endInEdges = _graph->EndEdges( node )
 _DynamicGraph::EdgeIterator outEdge = _graph->BeginEdges( node ), endOutEdges = _graph->EndEdges( node )
```
I think something similar could be used here i just need to figure it out.

**Comment by brano543** [comment]
Okay i think the solution is to insert all edges into one big array and store for every node indexes to edge array for incoming and outgoing edges for the current node.

**Comment by ben-strasser** [comment]
Hi,
>
> I have examined your parser and you remove a lot of edges from the 
> graph. This is why you don´t need so much space. For instance for 170 
> MB PBF Slovakia country extract i insert 4 million edges, while you 
> insert just 1 million. I was having trouble nicely printing 
> path,because there were some really sharp edges between points and 
> this created line segment which was outside of road printed on 
> OpenStreetMap road.
>
Degree 2 nodes are best handled outside of any routing engine. The way 
to go here is to put them into an edge attribute that the routing engine 
does not need to know of.

Best Regards
Ben Strasser

**Comment by brano543** [comment]
Are you currently storing for each way only first and last node id? I just briefly checked the parser and according to this part it seems so
```
if(osm_node_id_list.size() >= 2 && is_way_used_for_routing(osm_way_id, tags)){
				map.is_routing_way.make_large_enough_for(osm_way_id);
				map.is_routing_way.set(osm_way_id);

				for(std::uint64_t osm_node_id : osm_node_id_list) {
					map.is_modelling_node.make_large_enough_for(osm_node_id);
					if(map.is_modelling_node.is_set(osm_node_id)) {
						map.is_routing_node.make_large_enough_for(osm_node_id);
						map.is_routing_node.set(osm_node_id);
					} else {
						map.is_modelling_node.set(osm_node_id);
					}
				}

				assert(map.is_modelling_node.is_set(osm_node_id_list.front()));
				assert(map.is_modelling_node.is_set(osm_node_id_list.back()));

				map.is_routing_node.make_large_enough_for(osm_node_id_list.front());
				map.is_routing_node.set(osm_node_id_list.front());
				map.is_routing_node.make_large_enough_for(osm_node_id_list.back());
				map.is_routing_node.set(osm_node_id_list.back());
}
```
You are right, i will need some external data structure which keeps track of the nodes between each start and end node of way.

**Comment by brano543** [comment]
Maybe i should take into account all the nodes which are at intersection of two or more ways - indegree of node > 2 in case i would want to add turn restrictions later.

**Comment by ben-strasser** [comment]
Hi,

On 10/25/2016 08:42 PM, John Malcow wrote:
> Are you currently storing for each way only first and last node id?

Way endpoints and way intersections are routing nodes. Everything else is skipped.

Best Regards
Ben Strasser
