### ISSUE TITLE
Undirected version of CCH

### ISSUE THREAD

**Issue by Jiaweeeeeen** [RoutingKit/RoutingKit#114]
Hi,

We are working on a customisable labelling method for distance queries, which utilises Contraction Hierarchies (CH) to assist with the labelling construction. Our focus is on undirected graphs, and we were wondering if there is an undirected version of RoutingKit available for us to make fair experiments?

Thank you very much.

**Comment by airof98** [comment]
is Undirected graphs like graphs for walking ?

**Comment by Jiaweeeeeen** [comment]
Yes, it's similar to graphs used for walking. We are currently focusing on graphs without edge directions, so direct comparisons would not be accurate and equal.

**Comment by GrahamAsher** [comment]
What is the motivation for using an undirected graph? It can produce the same correct routes as a directed graph. As far as I can see the advantages are speed of data preparation, smaller size of data, and probably slightly faster route calculation. But if the performance differences are insignificant, and there is plenty of space for the data, one should use a standard directed graph.GrahamOn 8 Aug 2024, at 08:26, Jiaweeeeeen ***@***.***> wrote:﻿
Yes, it's similar to graphs used for walking. We are currently focusing on graphs without edge directions, so direct comparisons would not be accurate and equal.

**Comment by ben-strasser** [comment]
There is no undirected version in RoutingKit. However, depending on what you want you can get close.

For the regular CH, you can run the construction on a directed graph where the weights in both directions are the same. In this case, the upward and backward search graphs computed will be identical. If you want to estimate memory consumption of the CH, just only count one of them. If you want an undirected CH search graph, just pick one and throw away the other.

I do not expect any significant speedups for CH computation but there might be one. However, the RoutingKit CH is not tuned for preprocessing running time anyway. Quality of the computed CH was the main objective.

For CH queries, running times, I do not expect any impact.

For CCH, the contraction order computation is identical. No byte changes if you make things undirected.  

In the CCH customization, you enumerate the same triangles in the directed and undirected cases. However, in the undirected case, you do half the work per triangle. I guess here being undirected could actually make an impact. In the [CCH journal paper](http://ben-strasser.net/paper/customizable_contraction_hierarchies_acm_j_exp_algorithmics.pdf) in table IX there are some numbers. TLDR: Has some impact. Not the factor 2 one might expect.

I you really want precise numbers for the undirected case, you will have to implement an undirected customization. I do not expect this to be difficult.

For CCH queries, both regular and elimination tree, running times, I do not expect any impact.

Hope this helps!

**Comment by Jiaweeeeeen** [comment]
> What is the motivation for using an undirected graph? It can produce the same correct routes as a directed graph. As far as I can see the advantages are speed of data preparation, smaller size of data, and probably slightly faster route calculation. But if the performance differences are insignificant, and there is plenty of space for the data, one should use a standard directed graph.GrahamOn 8 Aug 2024, at 08:26, Jiaweeeeeen ***@***.***> wrote:﻿ Yes, it's similar to graphs used for walking. We are currently focusing on graphs without edge directions, so direct comparisons would not be accurate and equal. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Hi, thank you for your response and for asking about our motivation. We completely agree that the optimal route remains consistent. Our primary interest lies in the customization speed. In our project, we also employ the three-phase approach (preprocessing, customization, and query) to make our labelling method customizable. We have developed our own hierarchy for the contraction order and labelling initialization, and we customize the contraction hierarchy by enumerating all lower triangles. However, in our experiments, we found that our customization phase is slightly slower than CCH, excluding the time for labelling computation. This prompted us to investigate the factors contributing to these differences, which is why we are seeking a fair comparison using either both undirected or both directed versions.

**Comment by Jiaweeeeeen** [comment]
> There is no undirected version in RoutingKit. However, depending on what you want you can get close.
> 
> For the regular CH, you can run the construction on a directed graph where the weights in both directions are the same. In this case, the upward and backward search graphs computed will be identical. If you want to estimate memory consumption of the CH, just only count one of them. If you want an undirected CH search graph, just pick one and throw away the other.
> 
> I do not expect any significant speedups for CH computation but there might be one. However, the RoutingKit CH is not tuned for preprocessing running time anyway. Quality of the computed CH was the main objective.
> 
> For CH queries, running times, I do not expect any impact.
> 
> For CCH, the contraction order computation is identical. No byte changes if you make things undirected.
> 
> In the CCH customization, you enumerate the same triangles in the directed and undirected cases. However, in the undirected case, you do half the work per triangle. I guess here being undirected could actually make an impact. In the [CCH journal paper](http://ben-strasser.net/paper/customizable_contraction_hierarchies_acm_j_exp_algorithmics.pdf) in table IX there are some numbers. TLDR: Has some impact. Not the factor 2 one might expect.
> 
> I you really want precise numbers for the undirected case, you will have to implement an undirected customization. I do not expect this to be difficult.
> 
> For CCH queries, both regular and elimination tree, running times, I do not expect any impact.
> 
> Hope this helps!

Thank you very much for the detailed explanation and suggestions. We will implement the undirected customization or modify our code to work with directed graphs.
