### ISSUE TITLE
Doesn't compile under MacOS / with Xcode

### ISSUE THREAD

**Issue by joelhaasnoot** [RoutingKit/RoutingKit#12]
Compilation fails with following errors on MacOS Sierra 10.12.1 and Xcode 8.1 (with command line tools)

```
src/bit_vector.cpp:160:23: error: use of undeclared identifier 'aligned_alloc'
                data_ = (uint64_t*)(aligned_alloc(64, get_uint8_count(size)));
                                    ^
src/bit_vector.cpp:176:23: error: use of undeclared identifier 'aligned_alloc'
                data_ = (uint64_t*)(aligned_alloc(64, get_uint8_count(size)));
                                    ^
src/bit_vector.cpp:211:31: error: use of undeclared identifier 'aligned_alloc'
        data_(static_cast<uint64_t*>(aligned_alloc(64, get_uint8_count(o.size_)))), size_(o.size_){
```

Any ideas?

**Comment by skinkie** [comment]
Maybe create a nice macro here... https://github.com/RoutingKit/RoutingKit/blob/master/src/bit_vector.cpp#L12

**Comment by ben-strasser** [comment]
Hi,

Thanks for reporting the issue. On what GCC or Clang version is Xcode 8.1 based?

We are always interested in hearing in what context people use our software. Would you mind briefly summarizing you application? :)

There are portable implementations of these function commented out at the top of bit_vector.cpp. Uncomment those and the errors should go away.

Best Regards
Ben Strasser

**Comment by joelhaasnoot** [comment]
Hi Ben,
I uncommented those indeed, that brings me a little further, just to error on the following:
```
g++ -Wall -O3 -DNDEBUG -march=native -std=c++11 -fPIC -Iinclude  -c src/buffered_asynchronous_reader.cpp -o build/buffered_asynchronous_reader.o
src/buffered_asynchronous_reader.cpp:142:55: error: no member named 'to_string' in namespace 'std'
                throw std::runtime_error("Requested to read " +std::to_string(size)+" bytes, which is more than the block size of "+std::to_string(impl->block_size));
                                                               ~~~~~^
src/buffered_asynchronous_reader.cpp:142:124: error: no member named 'to_string' in namespace 'std'
                throw std::runtime_error("Requested to read " +std::to_string(size)+" bytes, which is more than the block size of "+std::to_string(impl->block_size));
                                                                                                                                    ~~~~~^
src/buffered_asynchronous_reader.cpp:178:51: error: no member named 'to_string' in namespace 'std'
                throw std::runtime_error("Wanted to read "+std::to_string(size)+" bytes but not enough are available in the data source.");
                                                           ~~~~~^
3 errors generated.
```
Seems to be related to the definition of c++1?

Xcode 8.1 is listed as being:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
I switched the makefile to use gcc 5.4 which I installed with Homebrew, that seems to work, but the default xcode-configuration doesn't.

**Comment by ben-strasser** [comment]
Hi,

does adding a #include <string> at the top of 
src/buffered_asynchronous_reader.cpp help?

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
@ben-strasser you may want to review https://github.com/bliksemlabs/RoutingKit/commit/d08b5135608c863a5480b813c92b1a5807b0da99

**Comment by ben-strasser** [comment]
Hi,

if I interpret the changes correctly, then they consists of removed trailing whitespace and is_sorted_using_less moved at the end of the header. I already moved is_sorted_using_less to the file end some time ago, i.e., that change is already in the master. What change do you want to point out?

https://github.com/RoutingKit/RoutingKit/blob/master/include/routingkit/sort.h 

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
```
src/customizable_contraction_hierarchy.cpp:18:10: fatal error: 'omp.h' file not found
#include <omp.h>
```
That is the fundamental problem. I recall that removing references to customizable_contraction_hierarchy.cpp solved the compilation for me with clang.

**Comment by ben-strasser** [comment]
What Clang version do you have? <omp.h> is part of OpenMP which is enabled using -fopenmp. Apparently, Clang only supports it since version 3.8.0, which is a pretty recent version. GCC supports it since years.

You can get the file to compile by removing the include and replace omp_get_num_procs() by 1 and ignoring all #pragma omp related warnings. Everything should work, except that the "parallelized" code will only use one thread.

**Comment by skinkie** [comment]
That was what I was thinking as well, but unless you have seen it working, this is probably the issue for Xcode not eating it.

```
clang version 3.8.0 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by ben-strasser** [comment]
Hi,

I commited a patch that makes the code compile without OpenMP support. Unfortunately, the parallelization request by the user is now silently ignored, if OpenMP is not present. :/ Not ideal but better than the status quo. 

Best Regards
Ben

**Comment by skinkie** [comment]
I have just tried to compile with your latest commit. It still complains on the missing omp.h.

**Comment by ben-strasser** [comment]
does removing the -fopenmp from the Makefile help?

**Comment by skinkie** [comment]
Works as a charm! Thanks.

**Comment by ben-strasser** [comment]
Good that it works. :) 

Do I understand the current situation correctly, in that under MacOS-clang the -fopenmp parameter defines the _OPENMP macro without actually enabling OpenMP support? One can therefore not rely on the _OPENMP macro to indicate whether OpenMP is active?

**Comment by skinkie** [comment]
Actually I tested it on Linux, but I think @joelhaasnoot can check on his shiny new MacBook Pro if your solution works.
