### ISSUE TITLE
Weird graph problem

### ISSUE THREAD

**Issue by brano543** [RoutingKit/RoutingKit#14]
Hello Ben,

i have reworked the graph as we discussed before. Now only the routing nodes are being used. Thank you for your valuable insights and now i realized that using arrays for best cost so far and visited was a brilliant idea, as i can very easily check for visited and best cost for given node.

However one "small thing" still bothers me and i can not figure out what the problem may be. On some crossroads, somehow the algorithm chooses node from another way,because you can turn there and also from that point it was possible to get back on the road i was currently in. I don't know what am i doing wrong,there is like no way for me to check if that node is really missing or what is the problem. I have checked the same route what OSRM finds. They find exactly the same route,but they don't have those glitched 2 nodes i have.
![wrong_vertex](https://cloud.githubusercontent.com/assets/6738774/20040103/92ce733e-a451-11e6-87b1-103018fbf5f1.jpg)

**Comment by brano543** [comment]
UPDATE
I have found a wonderful site called http://map.comlu.com/ which shows that i am missing turn restrictions. There is no other way it seems then to keep track of record of form
<FromNode,ViaNode,ToNode,Allowed> where the first three values should be key in hash map. Do you have a better idea? 

I am also not so familiar how new C++ sends functions as parameter,but you have something working with log_message in contractor. I think we should add a function as parameter to ContractionHierarchyQuery which will call a function every time a neighbor arc is checked. Meaningly in functions forward_expand_upward_ch_arcs_of_node and forward_can_stall_at_node 
```
for(unsigned arc = forward_first_out[node]; arc < forward_first_out[node+1]; ++arc){
unsigned h = forward_head[arc], d = distance_to_node + forward_weight[arc];

//current_node = node
//neihgbor = h
//current_node_parent = forward_predecessor_node[node]
//call function to evaluate if (current_node, neighbor, current_node_parent) exists in turn restrictions
//and has positive flag,so it allows this turn
```

**Comment by ben-strasser** [comment]
Hi,

the usual way to handle turn costs is to construct a turn-expanded graph.

The nodes of the turn-expanded graph are the directed edges of the graph that you already have. Add an edge in the expanded graph if you are allowed to "turn". "turning" in this context includes going straight. You will want to forbid x->y->x turns in nearly all cases.

The algorithm that you propose is, as far as I can tell, not correct. A node can be visited from multiple sides. Even though one is forbidden another one might not be.

Currently the RoutingKit PBF parser does not extract the turn restrictions. Fortunately, it can parse OSM relations though. Extracting turn restrictions would definitely be useful, but I wont have time in the near future to implement this unfortunately. Further, one can compute the CCH node orders faster by computing an edge ordering for the unexpanded graph. 

The simplest hack, that unfortunately only mitigates the problem and can cause new problems, consists of increasing the weights of the edge yz for every xyz restriction. 

Best Regards
Ben Strasser

**Comment by brano543** [comment]
Hello Ben,

thanks for valuable information. Just out of curiosity, i was reading the original Contraction Hierarchy paper and i want to ask you a question. How did you figure out this formula to get good node ordering?
` 1 + 1000*level + (1000*added_arc_count) / removed_arc_count + (1000*added_hop_count) / removed_hop_count;`
And also what is the difference between variables rank and order. I understand the rank is the level of the node used while doing the Dijkstra search.

**Comment by ben-strasser** [comment]
Hi,

> thanks for valuable information. Just out of curiosity, i was reading 
> the original Contraction Hierarchy paper and i want to ask you a 
> question. How did you figure out this formula to get good node ordering?
> |1 + 1000*level + (1000*added_arc_count) / removed_arc_count + 
> (1000*added_hop_count) / removed_hop_count;|
>
A combination of trial and error and reading what other peoples do.

> And also what is the difference between variables rank and order. I 
> understand the rank is the level of the node used while doing the 
> Dijkstra search.
>
rank == invert_permutation(order)

Best Regards
Ben Strasser
