### ISSUE TITLE
Pedestrian code

### ISSUE THREAD

**Issue by skinkie** [RoutingKit/RoutingKit#21]
Are you sure this code is right?

https://github.com/RoutingKit/RoutingKit/commit/2e17e4658b2bee706be11073d3ac00f96661011e#diff-54f00b3a2bc660e1fbdba1d5e0608f04R86

**Comment by ben-strasser** [comment]
Hi,

thanks for double checking the code. :)

> This code doesn't look right. access = yes => false thus return false

``
if(!str_eq(access, "yes") && X)
  return false;
``
If "access" is "yes" then "str_eq(access, "yes")" is true then "!str_eq(access, "yes")" is false then "!str_eq(access, "yes") && X" is false and "if("!str_eq(access, "yes") && X) return false;" does not return false. Is my logic wrong?

I thought that removing a level of parenthesis makes the code clearer.

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
Got it. Thanks.

Brain didn't pick up the "return false" was the only thing we want to return for.
