### ISSUE TITLE
Undefined reference to `RoutingKit::BitVector::BitVector()'

### ISSUE THREAD

**Issue by brano543** [RoutingKit/RoutingKit#22]
Hello,

i have encountered this problem when trying to put this logic
`ContractionHierarchy ch = ContractionHierarchy::load_file(edgesFileName);`
inside an function. It only works in main, but has somewhat problem inside any class member function. What can be the problem? 

I mean it works when it is defined inline header,but not when i split definition and implementation to .h and .cpp.
```
class Test
{
    public:
      void test();
};
void Test::test()
{
    ContractionHierarchy ch = ContractionHierarchy::load_file("edgesFileName");
}
```
will not compile while 
```
class Test
{
    public:
      void test()
      {
        ContractionHierarchy ch = ContractionHierarchy::load_file("edgesFileName");
      };
};
```
works without problem.

**Comment by ben-strasser** [comment]
Hi,

can you provide a minimal example that exhibits the problem? I can unfortunately not reproduce the problem from the information that you provided.

Best Regards
Ben Strasser

**Comment by brano543** [comment]
Hello,

i was about to send you additional details when i read the error report again. In one of my test application i forgot to add all .cpp in CMakeLists.txt. Thank you Ben for confirming this was issue on my side, i would have not found the problem otherwise. Now i can have ContractionHierarchy stored in graph class and can send to every thread this object which creates in each thread own ContractionHierarchyQuery.
