### ISSUE TITLE
RoutingKit capabilities

### ISSUE THREAD

**Issue by GrahamAsher** [RoutingKit/RoutingKit#23]
I'd like to know the answer to these questions about RoutingKit; believe me, I have tried other ways of finding the answers, but to no avail.

Can it handle turn restrictions (e.g., 'no right turn')?
Does it allow time delays to be assigned to turn types or, say, according to the presence of traffic lights?
Does it allow a route to pass through the same junction twice?

These questions could also be put as a single one: how easy is it to set up RoutingKit so that nodes are road segments and arcs are links between segments (i.e., turns)? That's the reverse of the normal way but makes it easier to assign costs to turns.

Allowing a route to pass through a junction twice makes it possible for a driver to go North through a junction, turn round and come back South through the junction, which can be the best way to get a journey started.

**Comment by ben-strasser** [comment]
If you have a data source tat provides a turn-expanded graph (i.e., 
nodes are roads, arcs are turns) then it will work. The current OSM 
parser unfortunately does not provide this feature.

**Comment by GrahamAsher** [comment]
Ben, thank you for your quick answer. It might be a good idea to document this fact and its implications on the main documentation page for RoutingKit. The important consequence is that RoutingKit, if using the current OSM parser, will often provide incorrect routes which contain illegal turns.

**Comment by ben-strasser** [comment]
Update: The parser now extracts turn restrictions. Turn expanded graph is not yet in RoutingKit

**Comment by GrahamAsher** [comment]
Hi Ben, after a long delay I have finally implemented turn-expanded graph routing using RoutingKit in my product, CartoType, and it works fine. Given the relatively short time it took to implement, and the high speed of both routing and creating the data that have been achieved, I now wish I'd done it three years ago. Well done RoutingKit team!

Implementation notes: I import the data (which doesn't have to be from OSM) into my non-CH turn-expanded router then create a RoutingKit CH object in the normal way. I then extract the shortcuts and add them to the data, which I write out to the map file using a serialised format. At query time the data is not all loaded into memory at once; I use a caching system to save runtime RAM.

**Comment by ben-strasser** [comment]
Thanks for the feedback. Good to hear that it works in your setting. :)
