### ISSUE TITLE
Segmentation fault after installation

### ISSUE THREAD

**Issue by skinkie** [RoutingKit/RoutingKit#4]
I have modified the Makefile a bit to get a proper output for this bug report;

If the ```nodeid``` mentioned shouldn't be interpreted as osm-node-id, I would suggest to change the example.

```
(gdb) r
Starting program: /home/skinkie/Sources/RoutingKit/main 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffde5fc700 (LWP 8900)]
[New Thread 0x7fffc5dfa700 (LWP 8901)]
3885634950
1508533156
[Thread 0x7fffde5fc700 (LWP 8900) exited]
[Thread 0x7fffc5dfa700 (LWP 8901) exited]
[New Thread 0x7fffde5fc700 (LWP 8905)]
[New Thread 0x7fffc5dfa700 (LWP 8906)]
[Thread 0x7fffde5fc700 (LWP 8905) exited]
[Thread 0x7fffc5dfa700 (LWP 8906) exited]

Thread 1 "main" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b60134 in RoutingKit::ContractionHierarchyQuery::add_source (
    this=0x7fffffffe110, external_s=3885634950, dist_to_s=0)
    at src/contraction_hierarchy.cpp:1477
1477            unsigned s = ch->rank[external_s];
(gdb) bt
#0  0x00007ffff7b60134 in RoutingKit::ContractionHierarchyQuery::add_source (
    this=0x7fffffffe110, external_s=3885634950, dist_to_s=0)
    at src/contraction_hierarchy.cpp:1477
#1  0x0000000000404fe9 in main () at main.cpp:28
(gdb) list
1472    ContractionHierarchyQuery&ContractionHierarchyQuery::add_source(unsigned external_s, unsigned dist_to_s){
1473            assert(ch && "query object must have an attached CH");
1474            assert(external_s < ch->node_count() && "node out of bounds");
1475            assert(state == query_state_initialized || state == query_state_target_pinned);
1476
1477            unsigned s = ch->rank[external_s];
1478
1479            if(!forward_queue.contains_id(s)){
1480                    forward_queue.push({s, dist_to_s});
1481                    forward_tentative_distance[s] = dist_to_s;
```

```
#include <routingkit/osm_simple.h>
#include <routingkit/contraction_hierarchy.h>
#include <routingkit/inverse_vector.h>
#include <routingkit/timer.h>
#include <iostream>
using namespace RoutingKit;
using namespace std;

int main(){
    // Load a car routing graph from OpenStreetMap-based data
    auto graph = simple_load_osm_car_routing_graph_from_pbf("/home/skinkie/osm/netherlands-latest.osm.pbf");
    auto tail = invert_inverse_vector(graph.first_out);

    // Build the index
    auto ch = ContractionHierarchy::build(
        graph.node_count(), 
        tail, graph.head, 
        graph.travel_time
    );

    // Besides the CH itself we need a query object. 
    ContractionHierarchyQuery ch_query(ch);

    // Use the query object to answer queries from stdin to stdout
    unsigned from, to;
    while(cin >> from >> to){
        long long start_time = get_micro_time();
        ch_query.reset().add_source(from).add_target(to).run();
        auto distance = ch_query.get_distance();
        auto path = ch_query.get_node_path();
        long long end_time = get_micro_time();

        cout << "To get from "<< from << " to "<< to << " one needs " << distance << " seconds." << endl;
        cout << "This query was answered in " << (end_time - start_time) << " microseconds." << endl;
        cout << "The path is";
        for(auto x:path)
            cout << " " << x;
        cout << endl;
    }
}
```

**Comment by ben-strasser** [comment]
Hi,

thanks for the bug report. Fortunately, I do not think that this is a 
bug but rather a documentation problem.
> |0x00007ffff7b60134 in 
> RoutingKit::ContractionHierarchyQuery::add_source ( 
> this=0x7fffffffe110, external_s=3885634950, dist_to_s=0)|
|3885634950 is a very large ID. This seems like an out-of-bounds error. 
Build RoutingKit without -DNDEBUG and an assert will fail in most cases 
where you pass invalid arguments to RoutingKit.

I think that 3885634950 is an OSM node ID and not a routing graph node 
ID. ||||Routing graph node ID| range from 0 to node_count-1 where 
node_count is the number of nodes contained in the routing graph. To map 
OSM node IDs to routing graph node ID you have two options:

1. Map the OSM node ID to ||||||a geographical position. Next you can 
use GeoPositionToNode to get the routing node ID. You can get the 
||||||||||||geographical positions|||| of the routing nodes, which are 
needed to construct the ||||||||||||GeoPositionToNode object,|||| using 
the latitude and longitude members of value returned by 
||||||||||||simple_load_osm_car_routing_graph_from_pbf.

2. Do not use the simplified PBF parser interface. Look at the 
implementation of simple_load_osm_car_routing_graph_from_pbf for a usage 
example of the more advanced interface. The object returned 
||||||||||||||||from load_osm_id_mapping_from_pbf contains an 
||||||||||||||||is_routing_node bitvector. Construct a LocalIDMapper 
object with this bitvector as parameter. The method 
LocalIDMapper::to_local then maps the OSM-node-ID to the corresponding 
routing-node-ID. If you also need to be able to map routing-nodes to 
OSM-node IDs then construct an IDMapper object, which additionally has a 
to_global method.
|||||||
Best Regards
Ben Strasser

PS: I'm always interested in learning about where people want/try to use 
RoutingKit. Would you mind briefly describing your application?
|

**Comment by skinkie** [comment]
Hi Ben,

Following a suggestion on [Twitter](https://twitter.com/pietercolpaert/status/784687095289970688) I wanted to run a benchmark on the 1:1 performance of CH. When using some numbers that are in the range of the expected node-id's - correctly implementing the geoindex was effort I didn't want to put in yesterday - I got a performance between 25-50ms for the same query on an Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz, and the memory usage is about 400MB.

Our current interest lies into 1:N output and intersections there of. For this endeavor I have implemented an OpenStreetMap parser based on O5M output, and a custom tag filter which results in road classifications. After which I run a topology extraction, topology mirror, and shrink functions. The shrink takes _much_ longer than RoutingKit which I am deeply impressed by, although I don't know what RoutingKit considers roads and what not (yet). My implementation ends up with 2583397 edges, and 1014128 nodes, where this output tailored to car routing.

After having implemented A* and got some considerate performance improvements choosing specific datastructures. Going from linear scan to khash resulted for A* in a ten fold improvement. After which I wanted to see how Dijkstra would work on khash + heap, khash alone, heap + our own [bitset](https://github.com/bliksemlabs/rrrr/blob/tdata4-csa/bitset.c), and bitset alone using [https://github.com/bliksemlabs/rrrr/blob/tdata4-csa/bitset.c#L131](next_set_bit) as queue. The speed was best on the third option. Most of the datastructures were already converted to column stores (instead of structs using lists) and one of the last improvements came out of this conversion.

Dijkstra now results into a stable performance of about 80ms and is able to get the shortest path for all nodes in The Netherlands.

In general we are interested in reachability and we are looking to get a walking/biking planner running orchestrated with our public transport journey planner.

Stefan

**Comment by ben-strasser** [comment]
Hi,

> I got a performance between 25-50ms for the same query on an Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz, and the memory usage is about 400MB.

This seems too slow. Try the following:

wget http://download.geofabrik.de/europe/netherlands-latest.osm.pbf
RoutingKit/bin/test_basic_features netherlands-latest.osm.pbf

It will run various tests and dump the results to the console. On stdout you get statistics and on stderr errors. If there is no output on stderr, then no test failed. In the statistics look for the "CH one-to-one distance query" line. On my laptop I get an average running time of about 29musec, which is about a factor 1000 faster than what you report. Did you construct a query object for every query? Constructing query objects is comparatively slow.

(You need to pull, the old version of test_basic_features did not measure running times.)

> Our current interest lies into 1:N output and intersections there of. 

Look into the pinned source/target feature. 

> The shrink takes /much/ longer than RoutingKit which I am deeply impressed by,

Thanks :)

> although I don't know what RoutingKit considers roads and what not (yet). 

The OSM tag logic is in osm_profile.cpp. The PBF parsing is done in osm_pbf_decoder.cpp and in osm_graph_builder.cpp. The parsing is independent of cars. osm_simple.cpp ties the two together providing a simple to use interface that "just works".

I would happily accept patches that extend osm_profile.cpp with reasonable default bicycle or pedestrian tag logic and extend osm_simple.cpp to provide a simple to use interface for these two cases.   

> My implementation ends up with 2583397 edges, and 1014128 nodes, where this output tailored to car routing.

test_basic_features finds 1105164 nodes and 2552220 directed arcs. This seems comparable.

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
On Mon, 10 Oct 2016, ben-strasser wrote:

> > I got a performance between 25-50ms for the same query on an Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz, and the memory usage is about 400MB.
> 
> This seems too slow. Try the following:

I stand corrected. It is 25-50 microseconds per iteration.


> > Our current interest lies into 1:N output and intersections there of.
> 
> Look into the pinned source/target feature.

I'll look into that. Given that the number of features requested; is 
there an optimisation possible over plain Dijkstra? When requesting all 
endpoints?


> > although I don't know what RoutingKit considers roads and what not (yet).
> 
> The OSM tag logic is in osm_profile.cpp. The PBF parsing is done in osm_pbf_decoder.cpp and in osm_graph_builder.cpp. The parsing is independent of cars. osm_simple.cpp ties the two together providing a
> simple to use interface that "just works".
> 
> I would happily accept patches that extend osm_profile.cpp with reasonable default bicycle or pedestrian tag logic and extend osm_simple.cpp to provide a simple to use interface for these two cases.

I think I am able to contribute something in that direction. Did someone 
already created a Python wrapper for RoutingKit?


Stefan

**Comment by ben-strasser** [comment]
Hi,

>> > Our current interest lies into 1:N output and intersections there of.
>>
>> Look into the pinned source/target feature.
> 
> I'll look into that. Given that the number of features requested; is
> there an optimisation possible over plain Dijkstra? When requesting all
> endpoints?

You can try pinning all target nodes. If that is not fast enough, it is possible to make the one-to-all special case faster but that is not (yet) implemented.

That being said, from my experience, you have a conceptual problem on a higher level if you need a one-to-all query. It's often one of those what-you-asked-for-but-not-what-you-wanted situations.

If you want to find all stops within a walking radius r you can do the following:

1. Build a GeoPositionToNode object with the stop positions (and not the positions of all nodes)
2. C = GeoPositionToNode::find_all_nodes_within_radius(lat, lon, r)
3. Run a query from s to all nodes in C filtering those that are below r.

I do not know whether it is faster to run |C| one-to-one queries or a single one-to-|C| query in step 3.

> Did someone already created a Python wrapper for RoutingKit?

None that I know of. 

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
> That being said, from my experience, you have a conceptual problem on a higher level if you need a one-to-all query. It's often one of those what-you-asked-for-but-not-what-you-wanted situations.

I can see at least one case where a visualisation of one-to-all requires to render the output. What solution would you propose for finding the best intersection points of multiple sets? The meet in the middle problem.

> If you want to find all stops within a walking radius r you can do the following:
> 
> 1. Build a GeoPositionToNode object with the stop positions (and not the positions of all nodes)
> 2. C = GeoPositionToNode::find_all_nodes_within_radius(lat, lon, r)
> 3. Run a query from s to all nodes in C filtering those that are below r.

I'll see if I can come up with some example implementations.

> None that I know of.

I'll add a RoutingKit Python Wrapper then to my todo list as well.

**Comment by ben-strasser** [comment]
Hi,

On 10/10/2016 04:13 PM, Stefan de Konink wrote:
>     That being said, from my experience, you have a conceptual problem on a higher level if you need a one-to-all query. It's often one of those what-you-asked-for-but-not-what-you-wanted situations.
> 
> I can see at least one case where a visualisation of one-to-all requires to render the output. What solution would you propose for finding the best intersection points of multiple sets? The meet in the middle problem.

I do not understand what you are trying to do. Do you want to find all nodes equidistant from two given nodes?

Best Regards
Ben Strasser

**Comment by skinkie** [comment]
Equidistant from two nodes. I would see that not all data is required if _only_ the possible Points-of-Interests are evaluated as targets.
