### ISSUE TITLE
Optimize loading time for larger PBF files.

### ISSUE THREAD

**Issue by xydinesh** [RoutingKit/RoutingKit#42]
I'm using http://download.geofabrik.de/north-america-latest.osm.pbf file. It is about 8GB and takes about 20min load everything to memory. Is there anything we can do to load this file faster ? Something like, saving preprocessed filess and provide it as input etc.

**Comment by xydinesh** [comment]
I tried approach in #34, still takes about same time and memory.

**Comment by ben-strasser** [comment]
On my test machine where the data comes from a 100 mbit NFS mount, the code needs a bit more than 5 min. Do you have a slow disk? Are you using Windows?

The imported data essentially conists of vector<unsigned>s. Feel free to use whatever you want to store these. Some simple functions are in vector_io.h

**Comment by xydinesh** [comment]
I'm using r4.4xlarge AWS instance with SSD (ubuntu) to load data. It is still taking about ~20min to read data, build index and create ContractionHierachey. Ill take a look at vector_io.h, thanks !

**Comment by ben-strasser** [comment]
Hi,

building the CH is what likely takes time here, not the PBF import itself. CHs have save-to-file-methods.

OSM import + CH for all of Northern America in 20 min is fast. I doubt that you will find a toolkit that is significantly faster.

Best Regards
Ben Strasser

**Comment by xydinesh** [comment]
I agree, other tools I've tried took more time. I hope saving CH to a file make make it faster. Will test that soon.
