### ISSUE TITLE
use RoutingKit library

### ISSUE THREAD

**Issue by rahelehzarei** [RoutingKit/RoutingKit#79]
Hi,

How can I use RoutingKit library(with all functionalities) in another c++ program in visual studio. Is it possible to use it for a c++ project in windows?

Best,
Raheleh

**Comment by ben-strasser** [comment]
It should be possible to get it to work in Visual Studio. As I do not have access to Visual Studio I cannot help you unfortunately. However, there have been reports in the past, that Windows is tricky.
