### ISSUE TITLE
Use the code in visual studio

### ISSUE THREAD

**Issue by rahelehzarei** [RoutingKit/RoutingKit#81]
Hi
Can I use the code in visual studio 2017? what changes do I need to make?

Thanks,
Raheleh

**Comment by ben-strasser** [comment]
It should be possible to get it to work in Visual Studio. As I do not have access to Visual Studio I cannot help you unfortunately. However, there have been reports in the past, that Windows is tricky.

**Comment by GrahamAsher** [comment]
I got it working in Visual Studio 2019 by defining

ROUTING_KIT_NO_GCC_EXTENSIONS
ROUTING_KIT_NO_POSIX

as preprocessor macros.
