### ISSUE TITLE
Obtaining Area way(points)

### ISSUE THREAD

**Issue by Feroslav** [RoutingKit/RoutingKit#83]
Hello, I must write at first, your library is amazing, thanks!
I stuck in situation, where i want obtain geo positions/waypoints of specific area,e.g. relation [#441573](https://www.openstreetmap.org/relation/441573)

Particular area ID got from _function<...>relation_callback_, called from _unordered_read_osm_pbf()_. 
I think that _std::vector<OSMRelationMember>&member_list_ contains "id", "type" and "role", and these "id" in specific type=way should be compared in _way_callback_, but i get nothing when i compare _osm_way_id_ or _osm_node_id_list_ from _way_callback_ function with _std::vector<OSMRelationMember>&member_list_ members, looks like _way_callback_ function jumping over some IDs.

Please, do you have idea how i can obtain area waypoints or list of geo position for particular area/boundaries?

**Comment by ben-strasser** [comment]
I do not fully understand your question. Could it be, that you are having problems because `unordered_read_osm_pbf` calls the callbacks in the order that the corresponding objects appear in the file? Relations usually come after the ways. This means that referencing a way ID in the `way_callback` that you got in the `relation_callback` is usually not so easy. What works is calling `unordered_read_osm_pbf` twice:
```cpp
#include <iostream>
#include <cstdint>
#include <unordered_set>
#include <routingkit/osm_decoder.h>
using namespace std;
using namespace RoutingKit;

int main(){
        std::unordered_set<unsigned>my_ways;
        unordered_read_osm_pbf(
		"in.pbf",
		nullptr,
                nullptr,
                [&](
			uint64_t osm_relation_id, const std::vector<OSMRelationMember>&member_list, const TagMap&tags
		){
			if(osm_relation_id == 441573){
                                for(OSMRelationMember mem : member_list){
                                        if(mem.type == OSMIDType::way)
                                                my_ways.insert(mem.id);
                                }
                        }
		}
        );
        unordered_read_osm_pbf(
		"in.pbf",
		nullptr,
                [&](uint64_t osm_way_id, const std::vector<std::uint64_t>&osm_node_id_list, const TagMap&tags){
                        if(my_ways.count(osm_way_id) > 0){
                                cout << "way " << osm_way_id << " has nodes";
                                for(uint64_t node:osm_node_id_list)
                                        cout << " " << node;
                                cout << endl;
                        }
                },
                nullptr
        );
}
```


Thanks for the feedback! :) I am always interested in where RoutingKit ends up and how it is used. If you do not mind, I'd love to hear about your usecase.

**Comment by Feroslav** [comment]
Ah, you are amazing! That is exactly what I wanted to do with relations/ways/nodes but i had no idea how achieve this because as you said, callbacks are processed serialized and relations was last in call scheme.

RoutingKit is perfect for routing capabilities and is really simple, ideal for my project which aims to localize walk distances between POI/Locations for hiking. 
Thanks a lot :), you make great tool.
