### ISSUE TITLE
directed graph

### ISSUE THREAD

**Issue by rahelehzarei** [RoutingKit/RoutingKit#85]
I was wondering where, in the code, you apply the weight to a directed graph, specifically where in the code one-way street are modeled?

**Comment by ben-strasser** [comment]
Arcs are directed. For two-way streets there are two arcs whereas for a one-way street there is only one arc.

**Comment by rahelehzarei** [comment]
Thank you for your response. 

To explain my issue precisely, I use CCH in another framework (SUMO) in which two-way streets are modeled as two separate edges, one with a positive id (i.e. +3) and the other one with a negative id(i.e. -3). 

When I feed this network to CCH, for some source-targets, I get a different shortest-path than with the other algorithms in that framework (Dijkstra, A-Star, and CH). It seems that CCH translates two edges with positive and negative id (edge and its reversed) as one edge with two directions, while it is not really street with two directions, but two different streets.  

One way to fix this would be in the customization phase: 1) check if there are two edges between two nodes, 2) then for each of these edges, 3) add another edge with assigning infinity as its weight. However, I'm not sure this is correct....Am I doing something wrong, and how do you recommend I fix this?

**Comment by ben-strasser** [comment]
I still do not really understand what you are trying to achieve. 

In all APIs, RoutingKit operates on a directed graph where nodes have integer ids 0 to n-1 and arcs have integer ids 0 to m-1.

In the RoutingKit CCH implementation (but not the RoutingKit CH implementation), undirected edges are used with two weights. One is upward and the other is downward. However, this is transparently translated at the CCH API boundaries and is not visible as long as you do not pock into the CCH implementation details.

**Comment by rahelehzarei** [comment]
I integrated CCH in the SUMO, but I noticed for some source-targets, it doesn't return the correct shortest path. When I investigated that, It seemed the reason is that SUMO implementation of a directed graph. In SUMO a two-way street is not a street with lanes in different directions, but two different arcs with different IDs(one positive one negative). For example, as you see in the image attached below, if one wants to go from edge 1 to edge -2, the shortest path will be 1,2,-2. It means they have to turn in node c and go to edge -2. what CCH returns is 1,2. So it seems, one street and its reversed (if exists), translated into one street with two directions and therefore for some trips (like 1 to -2) CCH doesn't return the correct path. I debug the CCH code, but it's not very clear for me where I need to do changes to make it consistent with SUMO. 
I think this should be fixed during customization when CCH gives two weights to each edge depending whether it's a one-way or two-way street. So for each arc and its reversed edge 4 weights should be defined. I would like to know if it's a correct approach or not.


![SUMONet](https://user-images.githubusercontent.com/35502343/80626289-37511700-8a1c-11ea-821d-d6cd118d1251.JPG)

**Comment by ben-strasser** [comment]
All routingkit IDs are from 0 to object_count - 1.  You put in negative ids. That is not between 0 and object_count-1. What you do cannot work.

The CCH code is definitely not broken with directed graphs.

Have you read [the documentation on graph representation](https://github.com/RoutingKit/RoutingKit/blob/master/doc/SupportFunctions.md)?

**Comment by rahelehzarei** [comment]
Yes, I change it before feeding to CCH. First I assign each node a number (range 0 to n-1) in a map data structure. Then iterate over all edges and for each edge, I make tail and head vector using that map. And the same for latitude and longitude of each node.  After making the order using inertial flow, I pass the node's order, tail, and head to CCH. So, everything is aligned with CCH graph representation. I read the documentation in Github and also ACM paper for Customizable Contraction Hierarchies. As I said, CCH returns correctly for some trips and wrong for some others, in my code. That's why I think it needs other modifications to integrate with SUMO.

**Comment by ben-strasser** [comment]
Can you provide a minimal example graph and code that shows the supposedly erroneous behavior?

From the info you provide, I can only wildly guess: Did you add arcs in both directions? If you have a two way road between nodes 42 and 54 then you need to have arcs 42->54 and 54->42. If you only have one of the two, then your road is a one-way road according to the model used by RoutingKit.
