### ISSUE TITLE
Does RoutingKit rely on unsigned being 32-bit?

### ISSUE THREAD

**Issue by r-barnes** [RoutingKit/RoutingKit#89]
The documentation says

> IDs in RoutingKit are always unsigned 32-bit integers.

However, RoutingKit internally uses the `unsigned` data type to store ids, but `unsigned` is not guaranteed to be 32-bits, although that's usually the case (https://en.cppreference.com/w/cpp/language/types).

A safer choice of data type would be `uint32_t` (http://www.cplusplus.com/reference/cstdint/), which is guaranteed to be 32 bits.

**Comment by ben-strasser** [comment]
In theory, this is true. In practice, no compiler can make `sizeof(unsigned) != 4`, as it would break far too much existing code. I do not see much value in changing RoutingKit.

BTW: One corner case where using `uint32_t` is very awkward is `printf`. You can no longer use "%u" as `uint32_t` might be an `unsigned long` under Windows. The correct way is to use `printf("%"PRIu32, ...)`. This quickly becomes completely unreadable.
